language: python
sudo: false
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install pytest pytest-pep8 pytest-flakes nose # we still need nose for the _eq functions for now
# command to run tests, e.g. python setup.py test
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
script: py.test
notifications:
  irc:
    channels:
      - "irc.nerv.fi#pyfibot"
    skip_join: true
