language: python
python:
  - "2.6"
  - "2.7"
env:
  - SETUP_TOOLS="<3.0"
  - SETUP_TOOLS=">=3.0"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip "setuptools$SETUP_TOOLS"
  - pip install --allow-all-external "argparse>=1.2.1"
  - pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: nosetests
notifications:
  irc:
    channels:
      - "irc.nerv.fi#pyfibot"
    skip_join: true
matrix:
  allow_failures:
    - env: SETUP_TOOLS=">=3.0"
